---
title: "git_01"
author: "Michelle Coleman"
date: "February 11,2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

Twinkle, Twinkle Little Bat  
How I wonder what you're at!  
Up above the world you fly,  
Like a tea tray in the sky.  
Twinkle, twinkle, little bat!  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
  
Lying, thinking  
Last night  
How to find my soul a home  
Where water is not thirsty  
And bread loaf is not stone  
I came up with one thing  
And I don't believe I'm wrong  
That nobody,  
But nobody  
Can make it out here alone.  
  
Alone, all alone  
Nobody, but nobody  
Can make it out here alone.  
  
There are some millionaires  
With money they can't use  
Their wives run round like banshees  
Their children sing the blues  
They've got expensive doctors  
To cure their hearts of stone.  
But nobody  
No, nobody  
Can make it out here alone.  